#!/bin/bash

LOGICAL_MONITORS=$(gdctl show | sed -n '/^Logical monitors:/,$p')

if grep -q "eDP-1" <<<"$LOGICAL_MONITORS"; then
  zenity --question --default-cancel --title="laptop-monitor-toggle" --text="Switch to Video Mode?"
  if [ $? -eq 0 ]; then
    gdctl set --layout-mode logical \
      --logical-monitor --monitor DP-4 --mode 1920x1080@60.000 --x 0 --y 0 --primary
    echo '<monitors version="2">
  <configuration>
    <layoutmode>logical</layoutmode>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DP-4</connector>
          <vendor>ACR</vendor>
          <product>Acer B273H</product>
          <serial>LJF0W0064350</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <disabled>
      <monitorspec>
        <connector>eDP-1</connector>
        <vendor>LGD</vendor>
        <product>0x032c</product>
        <serial>0x00000000</serial>
      </monitorspec>
      <monitorspec>
        <connector>DP-2</connector>
        <vendor>ACR</vendor>
        <product>Acer H236HL</product>
        <serial>LX1AA0034210</serial>
      </monitorspec>
    </disabled>
  </configuration>
</monitors> ' >~/.config/monitors.xml
  fi
else
  zenity --question --default-cancel --title="laptop-monitor-toggle" --text="Switch to Join Displays Mode?"
  if [ $? -eq 0 ]; then
    gdctl set --layout-mode logical \
      --logical-monitor --monitor eDP-1 --mode 1920x1080@60.150 --x 0 --y 0 \
      --logical-monitor --monitor DP-4 --mode 1920x1080@60.000 --x 1920 --y 0 --primary \
      --logical-monitor --monitor DP-2 --mode 1920x1080@60.000 --x 3840 --y 0
    echo '<monitors version="2">
  <configuration>
    <layoutmode>logical</layoutmode>
    <logicalmonitor>
      <x>3840</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>DP-2</connector>
          <vendor>ACR</vendor>
          <product>Acer H236HL</product>
          <serial>LX1AA0034210</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>eDP-1</connector>
          <vendor>LGD</vendor>
          <product>0x032c</product>
          <serial>0x00000000</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.150</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>1920</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>DP-4</connector>
          <vendor>ACR</vendor>
          <product>Acer B273H</product>
          <serial>LJF0W0064350</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
</monitors>' >~/.config/monitors.xml
  fi
fi
