#!/bin/bash

MONITOR_CONFIG=$(gdctl show)
LOGICAL_MONITORS=$(echo "$MONITOR_CONFIG" | sed -n '/^Logical monitors:/,$p')
# Ubuntu keeps changing my external monitor connector names. It seems to cycle
# between two sets, so the following should be enough to use the "correct"
# names. If it isn't, I can go further and actually parse the output to get
# serial numbers or something.
# FIXME: There may be an underlying issue: It seems like writing monitors.xml
# isn't enough for persistence. I may even be causing the connector name change
# by doing it. I could look to
# https://gitlab.com/knokelmaat/display-configuration-switcher-gnome-extension
# for ideas if need be
grep -q DP-4 <<<"$MONITOR_CONFIG"
if [ $? -eq 0 ]; then
  PRIMARY=DP-4
else
  PRIMARY=DP-3
fi
SECONDARY=DVI-I-4 # Acer
TERTIARY=DVI-I-3  # LG

if [ $(grep "Logical monitor #" <<<"$LOGICAL_MONITORS" | wc -l) -eq 3 ]; then
  zenity --question --default-cancel --title="" --text="Switch to Zen Mode?"
  if [ $? -eq 0 ]; then
    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/AllWindows --method org.gnome.Shell.Extensions.AllWindows.SavePositions
    gdctl set --layout-mode logical \
      --logical-monitor --monitor $PRIMARY --mode 1920x1080@60.000 --x 0 --y 0 --primary
    echo "<monitors version=\"2\">
  <configuration>
    <layoutmode>logical</layoutmode>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>${PRIMARY}</connector>
          <vendor>ACR</vendor>
          <product>Acer B273H</product>
          <serial>LJF0W0064350</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <disabled>
      <monitorspec>
        <connector>${SECONDARY}</connector>
        <vendor>ACR</vendor>
        <product>Acer H236HL</product>
        <serial>LX1AA0034210</serial>
      </monitorspec>
      <monitorspec>
        <connector>${TERTIARY}</connector>
        <vendor>GSM</vendor>
        <product>E2350</product>
        <serial>0x01010101</serial>
      </monitorspec>
    </disabled>
  </configuration>
  <configuration>
    <layoutmode>logical</layoutmode>
    <logicalmonitor>
      <x>3840</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>DP-2</connector>
          <vendor>ACR</vendor>
          <product>Acer H236HL</product>
          <serial>LX1AA0034210</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>eDP-1</connector>
          <vendor>LGD</vendor>
          <product>0x032c</product>
          <serial>0x00000000</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.150</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>1920</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>${PRIMARY}</connector>
          <vendor>ACR</vendor>
          <product>Acer B273H</product>
          <serial>LJF0W0064350</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
</monitors>" >~/.config/monitors.xml
  fi
else
  zenity --question --default-cancel --title="" --text="Switch to Join Displays Mode?"
  if [ $? -eq 0 ]; then
    gdctl set --layout-mode logical \
      --logical-monitor --monitor $TERTIARY --mode 1920x1080@60.000 --x 0 --y 0 \
      --logical-monitor --monitor $PRIMARY --mode 1920x1080@60.000 --x 1920 --y 0 --primary \
      --logical-monitor --monitor $SECONDARY --mode 1920x1080@60.000 --x 3840 --y 0
    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/AllWindows --method org.gnome.Shell.Extensions.AllWindows.RestorePositions
    echo "<monitors version=\"2\">
  <configuration>
    <layoutmode>logical</layoutmode>
    <logicalmonitor>
      <x>1920</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>${PRIMARY}</connector>
          <vendor>ACR</vendor>
          <product>Acer B273H</product>
          <serial>LJF0W0064350</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>${TERTIARY}</connector>
          <vendor>GSM</vendor>
          <product>E2350</product>
          <serial>0x01010101</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>3840</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>${SECONDARY}</connector>
          <vendor>ACR</vendor>
          <product>Acer H236HL</product>
          <serial>LX1AA0034210</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
  <configuration>
    <layoutmode>logical</layoutmode>
    <logicalmonitor>
      <x>3840</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>DP-2</connector>
          <vendor>ACR</vendor>
          <product>Acer H236HL</product>
          <serial>LX1AA0034210</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>0</x>
      <y>0</y>
      <scale>1</scale>
      <monitor>
        <monitorspec>
          <connector>eDP-1</connector>
          <vendor>LGD</vendor>
          <product>0x032c</product>
          <serial>0x00000000</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.150</rate>
        </mode>
      </monitor>
    </logicalmonitor>
    <logicalmonitor>
      <x>1920</x>
      <y>0</y>
      <scale>1</scale>
      <primary>yes</primary>
      <monitor>
        <monitorspec>
          <connector>${PRIMARY}</connector>
          <vendor>ACR</vendor>
          <product>Acer B273H</product>
          <serial>LJF0W0064350</serial>
        </monitorspec>
        <mode>
          <width>1920</width>
          <height>1080</height>
          <rate>60.000</rate>
        </mode>
      </monitor>
    </logicalmonitor>
  </configuration>
</monitors>" >~/.config/monitors.xml
  fi
fi
